class Graph:
    def __init__(self):
        self.graph = {
            'Addis Ababa': ['Ambo', 'Adama', 'Debre Birhan', 'Debre Markos'],
            'Adama': ['Assela', 'Ambo', 'Batu', 'Bishoftu', 'Dodola'],
            'Ambo': ['Addis Ababa', 'Adama', 'Nekemte', 'Wolkite'],
            'Assela': ['Adama', 'Dodola', 'Batu'],
            'Batu': ['Adama', 'Assela', 'Wolkite', 'Butajira'],
            'Bishoftu': ['Adama', 'Dukem'],
            'Debre Birhan': ['Addis Ababa', 'Debre Sina'],
            'Debre Markos': ['Addis Ababa', 'Finote Selam', 'Bahir Dar'],
            'Nekemte': ['Ambo', 'Assosa', 'Bedelle'],
            'Wolkite': ['Ambo', 'Hossana', 'Butajira', 'Jimma'],
            'Butajira': ['Batu', 'Wolkite', 'Hossana', 'Woliso'],
            'Debre Sina': ['Debre Birhan', 'Kemise'],
            'Finote Selam': ['Debre Markos', 'Bahir Dar'],
            'Bahir Dar': ['Finote Selam', 'Debre Markos', 'Azezo'],
            'Azezo': ['Bahir Dar', 'Gondar'],
            'Gondar': ['Azezo', 'Metemma'],
            'Metemma': ['Gondar'],
            'Kemise': ['Debre Sina', 'Kombolcha'],
            'Kombolcha': ['Kemise', 'Woldia'],
            'Woldia': ['Kombolcha', 'Lalibela', 'Sekota'],
            'Sekota': ['Woldia', 'Adigrat'],
            'Lalibela': ['Woldia'],
            'Adigrat': ['Sekota', 'Axum'],
            'Axum': ['Adigrat', 'Shire'],
            'Shire': ['Axum', 'Humera'],
            'Humera': ['Shire'],
            'Assosa': ['Nekemte', 'Gambela'],
            'Bedelle': ['Nekemte', 'Gore'],
            'Gore': ['Bedelle', 'Teppi'],
            'Teppi': ['Gore', 'Mizan Teferi'],
            'Mizan Teferi': ['Teppi', 'Tepi'],
            'Tepi': ['Mizan Teferi', 'Bonga'],
            'Bonga': ['Tepi', 'Jimma'],
            'Jimma': ['Bonga', 'Wolkite', 'Gimbie'],
            'Gimbie': ['Jimma', 'Metu'],
            'Metu': ['Gimbie', 'Assosa'],
            'Hossana': ['Butajira', 'Wolkite', 'Woliso'],
            'Woliso': ['Hossana', 'Butajira', 'Wolaita Sodo'],
            'Wolaita Sodo': ['Woliso', 'Hossana', 'Arba Minch'],
            'Arba Minch': ['Wolaita Sodo', 'Konso'],
            'Konso': ['Arba Minch', 'Jinka'],
            'Jinka': ['Konso', 'Turmi'],
            'Turmi': ['Jinka'],
            'Bale': ['Dodola', 'Goba', 'Goba'],
            'Dodola': ['Assela', 'Bale'],
            'Goba': ['Bale', 'Hirna'],
            'Hirna': ['Goba', 'Harar'],
            'Harar': ['Hirna', 'Dire Dawa'],
            'Dire Dawa': ['Harar', 'Gode'],
            'Gode': ['Dire Dawa', 'Jijiga'],
            'Jijiga': ['Gode', 'Hargeisa'],
            'Hargeisa': ['Jijiga'],
            'Dolo': ['Gode', 'Mogadishu'],
            'Mogadishu': ['Dolo'],
            'Juba': ['Dolo'],
            'Sof Oumer': ['Bale', 'Babile'],
            'Babile': ['Sof Oumer', 'Goba'],
            'Goba': ['Babile', 'Dega Habar'],
            'Dega Habar': ['Goba', 'Kebri Dahar'],
            'Kebri Dahar': ['Dega Habar', 'Verdha'],
            'Verdha': ['Kebri Dahar'],
            'Gambela': ['Assosa', 'Metu', 'Moyale'],
            'Moyale': ['Gambela', 'Hossana', 'Konso'],
            'Hossana': ['Moyale', 'Butajira'],
            'Butajira': ['Hossana', 'Wolkite'],
            'Wolkite': ['Butajira', 'Jimma'],
            'Jimma': ['Wolkite', 'Gimbie'],
            'Gimbie': ['Jimma', 'Metu'],
            'Metu': ['Gimbie', 'Assosa'],
        }

    graph_with_costs = {
        'Addis Ababa': [('Ambo', 1), ('Adama', 2), ('Debre Birhan', 3), ('Debre Markos', 4)],
        'Adama': [('Assela', 2), ('Ambo', 2), ('Batu', 1), ('Bishoftu', 1), ('Dodola', 5)],
        'Ambo': [('Addis Ababa', 1), ('Adama', 2), ('Nekemte', 3), ('Wolkite', 2)],
        'Assela': [('Adama', 2), ('Dodola', 3), ('Batu', 2)],
        'Batu': [('Adama', 1), ('Assela', 2), ('Wolkite', 1), ('Butajira', 2)],
        'Bishoftu': [('Adama', 1), ('Dukem', 1)],
        'Debre Birhan': [('Addis Ababa', 3), ('Debre Sina', 2)],
        'Debre Markos': [('Addis Ababa', 4), ('Finote Selam', 3), ('Bahir Dar', 5)],
        'Dodola': [('Adama', 5), ('Assela', 3), ('Bale', 4), ('Goba', 6)],
        'Nekemte': [('Ambo', 3), ('Gimbi', 4)],
        'Wolkite': [('Ambo', 2), ('Batu', 1), ('Hossana', 3)],
        'Finote Selam': [('Debre Markos', 3), ('Bahir Dar', 4)],
        'Bahir Dar': [('Finote Selam', 4), ('Debre Markos', 5), ('Gondar', 3)],
        'Gondar': [('Bahir Dar', 3), ('Azezo', 2)],
        'Azezo': [('Gondar', 2), ('Metema', 4)],
        'Metema': [('Azezo', 4)],
        'Gimbi': [('Nekemte', 4), ('Assosa', 6)],
        'Assosa': [('Gimbi', 6), ('Metekel', 5)],
        'Metekel': [('Assosa', 5), ('Finote Selam', 4)],
        'Hossana': [('Wolkite', 3), ('Butajira', 1), ('Wolaita Sodo', 3)],
        'Butajira': [('Batu', 2), ('Hossana', 1)],
        'Wolaita Sodo': [('Hossana', 3), ('Arba Minch', 4), ('Dawro', 3)],
        'Dawro': [('Wolaita Sodo', 3), ('Jimma', 4)],
        'Jimma': [('Dawro', 4), ('Bonga', 3)],
        'Bonga': [('Jimma', 3), ('Mizan Teferi', 4)],
        'Mizan Teferi': [('Bonga', 4), ('Tepi', 3)],
        'Tepi': [('Mizan Teferi', 3), ('Gore', 3)],
        'Gore': [('Tepi', 3), ('Gambela', 4)],
        'Gambela': [('Gore', 4), ('Bure', 5)],
        'Bure': [('Gambela', 5)],
        'Debre Sina': [('Debre Birhan', 2), ('Kemise', 3)],
        'Kemise': [('Debre Sina', 3), ('Dessie', 2)],
        'Dessie': [('Kemise', 2), ('Kobo', 3)],
        'Kobo': [('Dessie', 3), ('Woldia', 2)],
        'Woldia': [('Kobo', 2), ('Lalibela', 4)],
        'Lalibela': [('Woldia', 4), ('Sekota', 4), ('Debre Tabor', 4)],
        'Sekota': [('Lalibela', 4), ('Adigrat', 5)],
        'Debre Tabor': [('Lalibela', 4), ('Bahir Dar', 4)],
        'Adigrat': [('Sekota', 5), ('Adwa', 3)],
        'Adwa': [('Adigrat', 3), ('Axum', 2)],
        'Axum': [('Adwa', 2), ('Shire', 4)],
        'Shire': [('Axum', 4), ('Humera', 6)],
        'Humera': [('Shire', 6)],
        'Fanti Rasu': [('Gobi Rasu', 3)],
        'Gobi Rasu': [('Fanti Rasu', 3), ('Dessie', 5)],
        'Gode': [('Kebri Dehar', 2)],
        'Kebri Dehar': [('Gode', 2), ('Wardher', 3)],
        'Wardher': [('Kebri Dehar', 3), ('Jijiga', 5)],
        'Jijiga': [('Wardher', 5), ('Harar', 3)],
        'Harar': [('Jijiga', 3), ('Dire Dawa', 2)],
        'Dire Dawa': [('Harar', 2), ('Chiro', 3)],
        'Chiro': [('Dire Dawa', 3), ('Awash', 2)],
        'Awash': [('Chiro', 2), ('Adama', 3)],
        'Arba Minch': [('Wolaita Sodo', 4), ('Konso', 3)],
        'Konso': [('Arba Minch', 3), ('Yabelo', 2)],
        'Yabelo': [('Konso', 2), ('Moyale', 4)],
        'Moyale': [('Yabelo', 4)]
    }
    
# Instantiate and run search for question 2
search_graph_with_costs = SearchGraphWithCosts(graph_with_costs)
print("UCS from Addis Ababa to Lalibela:", search_graph_with_costs.ucs('Addis Ababa', 'Lalibela'))

if __name__ == "__main__":
    g = Graph()
    g.display_graph()
