class Graph:
    def __init__(self):
        self.graph = {
            'Addis Ababa': {'Ambo': 3, 'Adama': 2, 'Debre Birhan': 5, 'Debre Markos': 8},
            'Adama': {'Assela': 4, 'Ambo': 3, 'Batu': 3, 'Bishoftu': 1, 'Dodola': 7},
            'Ambo': {'Addis Ababa': 3, 'Adama': 3, 'Nekemte': 6, 'Wolkite': 4},
            'Assela': {'Adama': 4, 'Dodola': 6, 'Batu': 2},
            'Batu': {'Adama': 3, 'Assela': 2, 'Wolkite': 4, 'Butajira': 5},
            'Bishoftu': {'Adama': 1, 'Dukem': 2},
            'Debre Birhan': {'Addis Ababa': 5, 'Debre Sina': 4},
            'Debre Markos': {'Addis Ababa': 8, 'Finote Selam': 3, 'Bahir Dar': 5},
            'Finote Selam': {'Debre Markos': 3, 'Bahir Dar': 2},
            'Bahir Dar': {'Finote Selam': 2, 'Debre Markos': 5, 'Azezo': 3},
            'Azezo': {'Bahir Dar': 3, 'Gondar': 2},
            'Gondar': {'Azezo': 2, 'Metemma': 6},
            'Metemma': {'Gondar': 6},
            'Kemise': {'Debre Sina': 4, 'Kombolcha': 3},
            'Debre Sina': {'Debre Birhan': 4, 'Kemise': 4},
            'Kombolcha': {'Kemise': 3, 'Woldia': 4},
            'Woldia': {'Kombolcha': 4, 'Lalibela': 5, 'Sekota': 6},
            'Sekota': {'Woldia': 6, 'Adigrat': 5},
            'Lalibela': {'Woldia': 5},
            'Adigrat': {'Sekota': 5, 'Axum': 4},
            'Axum': {'Adigrat': 4, 'Shire': 3},
            'Shire': {'Axum': 3, 'Humera': 6},
            'Humera': {'Shire': 6},
            'Assosa': {'Nekemte': 5, 'Gambela': 7},
            'Nekemte': {'Ambo': 6, 'Assosa': 5, 'Bedelle': 4},
            'Bedelle': {'Nekemte': 4, 'Gore': 5},
            'Gore': {'Bedelle': 5, 'Teppi': 6},
            'Teppi': {'Gore': 6, 'Mizan Teferi': 3},
            'Mizan Teferi': {'Teppi': 3, 'Tepi': 2},
            'Tepi': {'Mizan Teferi': 2, 'Bonga': 4},
            'Bonga': {'Tepi': 4, 'Jimma': 3},
            'Jimma': {'Bonga': 3, 'Wolkite': 4, 'Gimbie': 6},
            'Gimbie': {'Jimma': 6, 'Metu': 3},
            'Metu': {'Gimbie': 3, 'Assosa': 5},
            'Hossana': {'Butajira': 5, 'Wolkite': 4, 'Woliso': 3},
            'Wolkite': {'Ambo': 4, 'Hossana': 4, 'Butajira': 4, 'Jimma': 4},
            'Butajira': {'Batu': 5, 'Wolkite': 4, 'Hossana': 5, 'Woliso': 6},
            'Woliso': {'Hossana': 3, 'Butajira': 6, 'Wolaita Sodo': 5},
            'Wolaita Sodo': {'Woliso': 5, 'Hossana': 4, 'Arba Minch': 5},
            'Arba Minch': {'Wolaita Sodo': 5, 'Konso': 3},
            'Konso': {'Arba Minch': 3, 'Jinka': 4},
            'Jinka': {'Konso': 4, 'Turmi': 5},
            'Turmi': {'Jinka': 5},
            'Bale': {'Dodola': 4, 'Goba': 3},
            'Dodola': {'Assela': 6, 'Bale': 4},
            'Goba': {'Bale': 3, 'Hirna': 4},
            'Hirna': {'Goba': 4, 'Harar': 5},
            'Harar': {'Hirna': 5, 'Dire Dawa': 3},
            'Dire Dawa': {'Harar': 3, 'Gode': 7},
            'Gode': {'Dire Dawa': 7, 'Jijiga': 4},
            'Jijiga': {'Gode': 4, 'Hargeisa': 5},
            'Hargeisa': {'Jijiga': 5},
            'Dolo': {'Gode': 8, 'Mogadishu': 6},
            'Mogadishu': {'Dolo': 6},
            'Juba': {'Dolo': 7},
            'Sof Oumer': {'Bale': 5, 'Babile': 4},
            'Babile': {'Sof Oumer': 4, 'Goba': 3},
            'Dega Habar': {'Goba': 6, 'Kebri Dahar': 5},
            'Kebri Dahar': {'Dega Habar': 5, 'Verdha': 7},
            'Verdha': {'Kebri Dahar': 7},
            'Gambela': {'Assosa': 7, 'Metu': 6, 'Moyale': 8},
            'Moyale': {'Gambela': 8, 'Hossana': 7, 'Konso': 6}
        }

    def get_neighbors(self, node):
        return self.graph.get(node, {})
