class RelaxedGraph:
    def __init__(self):
        self.graph = {
            'Addis Ababa': ['Ambo', 'Adama', 'Debre Birhan'],
            'Ambo': ['Addis Ababa', 'Nekemte', 'Wolkite'],
            'Adama': ['Addis Ababa', 'Matahara', 'Assela', 'Batu'],
            'Debre Birhan': ['Addis Ababa'],
            'Nekemte': ['Ambo', 'Gimbi', 'Bedelle'],
            'Wolkite': ['Ambo', 'Buta Jirra', 'Hossana', 'Jimma'],
            'Buta Jirra': ['Wolkite', 'Worabe'],
            'Worabe': ['Buta Jirra', 'Shashemene', 'Hossana'],
            'Hossana': ['Wolkite', 'Worabe', 'Wolaita Sodo'],
            'Shashemene': ['Worabe', 'Hawassa', 'Dodolla'],
            'Hawassa': ['Shashemene', 'Dilla'],
            'Dilla': ['Hawassa', 'Arba Minch'],
            'Arba Minch': ['Dilla'],
            'Jimma': ['Wolkite', 'Gore', 'Bonga'],
            'Gore': ['Jimma', 'Tepi', 'Gambella'],
            'Bonga': ['Jimma', 'Tepi'],
            'Tepi': ['Bonga', 'Gore'],
            'Gimbi': ['Nekemte', 'Dembi Dollo'],
            'Dembi Dollo': ['Gimbi', 'Gambella'],
            'Gambella': ['Gore', 'Dembi Dollo'],
            'Bedelle': ['Nekemte', 'Gore'],
            'Matahara': ['Adama', 'Awash'],
            'Awash': ['Matahara', 'Chiro'],
            'Chiro': ['Awash', 'Dire Dawa'],
            'Dire Dawa': ['Chiro', 'Harar'],
            'Harar': ['Dire Dawa', 'Babile'],
            'Babile': ['Harar', 'Jijiga'],
            'Jijiga': ['Babile', 'Dega Habor'],
            'Dega Habor': ['Jijiga', 'Kebri Dehar'],
            'Kebri Dehar': ['Dega Habor', 'Gode'],
            'Gode': ['Kebri Dehar'],
            'Dodolla': ['Shashemene', 'Assela', 'Bale'],
            'Assela': ['Adama', 'Dodolla'],
            'Batu': ['Adama', 'Shashemene'],
            'Bale': ['Dodolla', 'Goba', 'Sof Oumer'],
            'Goba': ['Bale'],
            'Sof Oumer': ['Bale'],
            'Dawro': ['Wolaita Sodo'],
            'Wolaita Sodo': ['Hossana', 'Dawro', 'Hawassa'],
            'Mezan Teferi': ['Tepi'],
        }
        self.utilities = {
            'Gambella': 5,
            'Dembi Dollo': 4,
            'Gimbi': 3,
            'Jimma': 6,
            'Gore': 4,
            'Tepi': 5,
            'Bonga': 5,
            'Dilla': 6,
            'Arba Minch': 7,
            'Sof Oumer': 7,
            'Goba': 8,
            'Bale': 8,
            'Dodolla': 6,
            'Hawassa': 5,
            'Harar': 9,
            'Jijiga': 7,
            'Dire Dawa': 8,
            'Chiro': 6,
            'Awash': 5,
            'Matahara': 4,
            'Adama': 6,
            'Debre Birhan': 4,
            'Ambo': 4,
            'Wolkite': 5,
            'Hossana': 6,
            'Worabe': 5,
            'Buta Jirra': 4,
            'Shashemene': 5,
            'Dega Habor': 6,
            'Kebri Dehar': 6,
            'Gode': 6,
        }

    def get_neighbors(self, node):
        return self.graph.get(node, [])

    def get_utility(self, node):
        return self.utilities.get(node, 0)
